### ISSUE TITLE
How to generate bootloader package using adafruit-nrfutil?

### ISSUE THREAD

**Issue by mattratto** [adafruit/Adafruit_nRF52_Bootloader#106]
I've built the current bootloader + softdevice using the code in this repo and have successfully updated a feather_nrf52832 using SWD. I'd like to try doing the same over serial, but can't seem to figure out the right combo to generate a working bootloader + softdevice package for use with adafruit-nrfutil DFU. 

packages created via: adafruit-nrfutil dfu genpkg --dev-type 0x0052 --bootloader bootloader.hex boot.zip 

result in error: Timed out waiting for acknowledgement from device. 

This occurs immediately after the DFU init packet is sent. 

The prebuilt binary packages that are included in the feather_nrf52832 BSP work fine, e.g. the following command executes and completes with no errors: 
adafruit-nrfutil --verbose dfu serial -pkg feather_nrf52832_bootloader-0.2.13_s132_6.1.1.zip -p COM18 -b 115200 --touch 1200

What are the proper commands to turn  feather_nrf52832_bootloader-0.2.13_s132_6.1.1.hex into a working package? 

thanks, 

Matt

**Comment by hathach** [comment]
for question, please post it to our support forum, also check out our tutorial and makefile. They have all information needed to generate the package file.
