### ISSUE TITLE
More details on resolving issues with Nordic nRF52840 Dongle and this bootloader

### ISSUE THREAD

**Issue by mikew67** [adafruit/Adafruit_nRF52_Bootloader#122]
1. Have attempted to replace the Nordic stock bootloader in their nRF52840 Dongle (PCA10059, v.1.0.0) device with this bootloader, but have failed, both using software only, and using a Nordic nRF52 Dev-Kit with the Dongle connected to the output of its JLink as an external device).  Ultimate goal is to be able to install CircuitPython.

1. Also, have tried to to replace the Dongle's bootloader using Nordic's desktop nrf Connect app with Programmer plug-in using pre-built hex files here.  Of course, that fails with the lack of a suitable signature for the hex file.

1. Have also installed Adafruit-nrfutil, but not clear how to use it.

Therefore, it would be very useful if you would provide two detailed step-by-step procedures, specifically for the Nordic nRF52840 (a somewhat peculiar device):

1. How to replace the stock bootloader in the Nordic nRF52840 Dongle with a software-only procedure (modulo a solder jumper).
2. How to use the new bootloader on the now-modified Dongle (e.g., white button, reset button instructions; leave the solder bridge in place?)

Many thanks.  You'll save me from repeating many frustrating moments.

**Comment by hathach** [comment]
1. You need a jlink and solder SWD on the dongle.
2. check out the readme.md

for more questions, please post/search on Adafruit forum support which is used for how-to. We use github mostly for code related developemnt.
