### ISSUE TITLE
Bootloader support for alternative SoftDevices

### ISSUE THREAD

**Issue by orrmany** [adafruit/Adafruit_nRF52_Bootloader#125]
**The problem**
Many nRF52 chips are capable of running alternative, particularly multi-protocol softdevices, such as nRF52832, nRF52840. It is understandable that Adafruit does not want to redistribute softdevices where the license does not permit that, such as the case for the ANT SoftDevices, but the complete lack of support for them is frustrating. One has to resort to manual hacking, see for example [my attempt](http://orrmany.hu/wiki/doku.php?id=arduino:s340_softdevice_adafruit_nrf52840_feather_express), but as soon as Adafruit releases a new version and the IDE installs that -- then the manual hacks are instantly broken. At-least some _skeleton_ support for equipping these boards with alternative soft-devices is needed.

**The solution I'd like**
A skeleton-support within the bootloader source-code, which lets me just drag-and-drop the .hex and header files for the alternative soft device and I'd be ready to compile.

**The alternatives I've considered**
- Not buying from Adafruit :-P (just joking)
- Manually hacking in the alternative SD, which is a fragile solution

**Additional context**
My feeble attempt for such support is in PR #124

**Comment by hathach** [comment]
closed since we have no plan and/or information to maintain other SoftDevice, but it should be easier to replace the stock Softdevice after #126 is implemented.
