### ISSUE TITLE
SPI Failure

### ISSUE THREAD

**Issue by ykqureshi** [adafruit/Adafruit_nRF52_Bootloader#135]
**Hardware Setup**
- Adafruit nrf52840 Feather Express
- Bootloader version: "feather_nrf52840_express_bootloader-0.3.2_s140_6.1.1"
- IDE: VS code with platformio

**Problem Description**
The SPI communication doesn't work when the board is powered up with battery alone. Otherwise works fine when USB is plugged in. The problem is mainly related to VBUS. When I supply the VBUS with external 5V everything seems to work fine.

**To Reproduce**
Simply program the board with any SPI example and power up the board with battery or any 3.3v source alone. It won't communicate.
- PINs used: SCK, MOSI, MISO and CS = D10

**Expected behavior**
In my case, I have connected a fingerprint sensor FPC BM-Lite which is communicating through SPI. The sensor gets initialized well when USB is plugged as shown below:
![IMG_20200529_004549](https://user-images.githubusercontent.com/7864849/83201830-a9fe0100-a146-11ea-8ccd-1a8aa7e4f60f.jpg)
But throws back communication error when USB is not plugged!!
![IMG_20200529_004617](https://user-images.githubusercontent.com/7864849/83201846-b6825980-a146-11ea-9f86-a2177a62f858.jpg)

**Data from logic analyzer**
When SPI is working fine I can easily see the communication
![2020-05-29](https://user-images.githubusercontent.com/7864849/83202085-20026800-a147-11ea-92e2-2d5481a166c5.png)

**Comment by hathach** [comment]
are you SURE this is the bootloader's bug !!!??? Bootloader don't even enable SPI peripheral at all !!!!

**Comment by ykqureshi** [comment]
> 
> 
> are you SURE this is the bootloader's bug !!!??? Bootloader don't even enable SPI peripheral at all !!!!

I am not 100% sure if this is directly related to bootloader but something wrong is happening in the very beginning. If I power up the board with USB then everything works fine otherwise  SPI doesn't work at all.

**Comment by dhalbert** [comment]
Maybe try this with a vanilla Arduino SPI program as well, as opposed to platformIO.

**Comment by ykqureshi** [comment]
I successfully tested the SPI with TFT module from Adafruit and it seems to fine. So I found a work around. I am initializing SPI TFT first and then initializing the fingerprint sensor. Problem solved. ;)
![IMG_20200529_233830](https://user-images.githubusercontent.com/7864849/83307732-a3828e80-a205-11ea-9c56-e45f2703e2ba.jpg)

Thanks for your responses. 👍
