### ISSUE TITLE
Trying to use on nRF52840 DK (PCA10056) [Bug]

### ISSUE THREAD

**Issue by tusharvb19** [adafruit/Adafruit_nRF52_Bootloader#138]
**Not working for me**

**Set up**
  - nRF52840 DK
  - Windows 10
  - No debug!!!

**To Reproduce**
1.  Connect DK and Flash bootloader using J-Link(Select board as nRF52840 DK, Tools - Burn bootloader while selecting Programmer as J-Link)
2. Now Flash the example bleuart using Upload using Programmer
3. No sign of working in nRF Connect mobile app

**Additional**
Also, Can you help to find the UART pins on nRF52840 DK?

**Comment by JoeBakalor** [comment]
Did you program the SoftDevice or just the bootloader?

**Comment by tusharvb19** [comment]
The Softdevice and Bootloader is included when we burn the bootloader, right?
I will confirm if both are installed using nRF connect pc-> Programmer!

**Comment by tusharvb19** [comment]
Now when I flashed the code using Sketch--> Upload using Programmer

![image](https://user-images.githubusercontent.com/20925909/84573781-520aff80-adc0-11ea-9109-13aa820de549.png)

No sign...LED1 slowly blinks continuously!
And not showing anything in nRF Connect mobile app!


What are the pins for TX and RX for serial port to check for serial prints!

**Comment by tusharvb19** [comment]
Anyone here to help me?

**Comment by hathach** [comment]
you need to upload using Serial/Uf2 at least once or write magic number to bypass firmware integrity check. For more question, please post on the support forum.

**Comment by huddy987** [comment]
@hathach I am seeing the same issue. I tried uploading using UF2 as well, can you confirm that this should work?

1. make board=pca10056 all
2. make board=pca10056 flash
3. make board=pca10056 sd

Then upload S140 to the device using UF2. I am able to see the drive in USB cdc, but when I load an app, it does not jump to app (led stays pulsing for some reason)
