### ISSUE TITLE
Question: Custom bootloader action?

### ISSUE THREAD

**Issue by crides** [adafruit/Adafruit_nRF52_Bootloader#141]
How can I go about modifying the bootloader so that I can have custom actions running? I have an external 16Mbyte QSPI flash that's used to store data, and I would like to update those data by using UF2. Of course I need to pull in the QSPI related code in order to manipulate the flash properly, but where else do I need to look into to achieve what I want? Thanks!

**Comment by hathach** [comment]
check out nordic nrfx for qspi flash driver then try to understand the bootloader code to see where it should be put to best implement what you need.
