### ISSUE TITLE
Why boot drive timeout?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_nRF52_Bootloader#164]
With this UF2bootloader (not the Atmel one), there is a timeout after several minutes when the boot drive disappears. Currently this seems to be causing a Finder crash in some circumstances. See https://forums.adafruit.com/viewtopic.php?f=65&t=168987.

@hathach Is the timeout deliberate? What was the motivation? Thanks.

**Comment by hathach** [comment]
Yes, the timeout is deliberate, it is there when we first started based on Nordic bootloader example. So I am not sure on the motivation either. We can remove it if you think it is better that way.

**Comment by dhalbert** [comment]
Yes,thanks,  then, let's remove it, since it's causing actual crashes on vulnerable hosts (which shouldn't happen). I can't remember, is there a self-updater yet, or did that turn out to be impossible or extremely difficult?

**Comment by kevinjwalters** [comment]
I timed an Adafruit CLUE (connected to a Windows host) at 300 (+/-1) seconds, btw. The posts mention 4 minutes. I assume this is just an estimation but it would be interesting if there is a difference here somewhere.

**Comment by hathach** [comment]
oh, the bootloader is already updated that does not time out when uf2 is mounted, we just haven't released it yet. Though, we can remove it all for good as well.
