### ISSUE TITLE
Not Compatible with Native Nordic SDK DFU Update Packages

### ISSUE THREAD

**Issue by uched41** [adafruit/Adafruit_nRF52_Bootloader#165]
Hello,
I have a production device running the adafruit_nrf52_bootloader (non_secure) which I am trying to update with a new DFU Zip Package built with nrfutil in the native NRF52 development environment. This OTA DFU fails. But when I try to update with a DFU Package built on the adafruit platform, the update is successful.

Are DFU Packages from both platforms cross-compatible?

I am using this Adafruit_nRF52_Bootloader with BLEDfu Service.

**Comment by hathach** [comment]
No it is not compatible, this is based on legacy bootloader.
