### ISSUE TITLE
nRF52811 Support

### ISSUE THREAD

**Issue by zwells** [adafruit/Adafruit_nRF52_Bootloader#180]
Any advice is appreciated.  I don't expect this to be added to the repo.

Which board variant would be closest to editing for 52811 support? It has an 832 package but with a 840 softdevice(s140).

I'm guessing in board.mk I would set MCU_SUB_VARIANT = nrf52840 and then use the 832 board.h for same pinout?

**Comment by hathach** [comment]
811 has very small flash, the bootloader size should be small enough, if being added you should optimize the layout since it doesn't have USB. Other than that you need to follow nordic recommendation kit for 811. I am also not familiar with 811 as well.
