### ISSUE TITLE
Circuit PG Bluefruit - Update over UF2 (mass-storage) without programmer

### ISSUE THREAD

**Issue by chatelao** [adafruit/Adafruit_nRF52_Bootloader#183]
**Is your feature request related to a problem? Please describe.**
Is it possible to update the "Circuit Playground Express Bluefruit" directly over UF2 instead of a programmer / .hex ?

n.b.: For the basic "Playground Express" updating with UF2 was so easy. Please include the output in this release packages too.

**Comment by hathach** [comment]
questions and how-to please post on our support forum

**Comment by chatelao** [comment]
Thanks for the hint & stay safe
