### ISSUE TITLE
[Bug] Updating the Bootloader to the latest 0.4.0 release

### ISSUE THREAD

**Issue by IeiuniumLux** [adafruit/Adafruit_nRF52_Bootloader#187]
I'm trying to update my [Adafruit Feather nRF52840](https://www.adafruit.com/product/4516) Sense board with the latest [0.4.0 Bootloader release](https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases/download/0.4.0/feather_nrf52840_sense_bootloader-0.4.0.zip) and the `adafruit-nrfutil` tool indicates that it was successfully upgraded, as shown below. However, the Arduino IDE still shows the previous version. 

<img width="845" alt="Screen Shot 2021-02-01 at 12 11 34 PM" src="https://user-images.githubusercontent.com/3729432/106513113-5d15bb80-6487-11eb-9a62-d30e95db0c8f.png">

<img width="794" alt="Screen Shot 2021-02-01 at 12 19 19 PM" src="https://user-images.githubusercontent.com/3729432/106513361-bb429e80-6487-11eb-89b0-c5386c628323.png">

I also tried to update it using the IDE (with Adafruit board and libraries updated) via the `Burn Booloader` menu option, but same result.  It completes successfully, but it continues showing the preview version 0.3.2.

**Comment by hathach** [comment]
no this is not a bug, Arduino doesn't have ability to detect the bootloader, the menu is just a mean to show the bootloader that will be burned by the IDE. To check the actual version double reset to get device into uf2 mode and check its `INFO.txt` file. Seem like this cause some confusion, maybe we could remove this menu in the future.

**Comment by IeiuniumLux** [comment]
@hathach, As you pointed out, the `INFO_UF2.TXT` shows the latest Bootloader 0.4.0 version.  Thanks!

<img width="771" alt="Screen Shot 2021-02-01 at 8 52 59 PM" src="https://user-images.githubusercontent.com/3729432/106554163-ab4ead00-64cf-11eb-8565-a219042a59e3.png">

**Comment by hathach** [comment]
I am glad that helps
