### ISSUE TITLE
[Bug] CI builds failing for pull requests

### ISSUE THREAD

**Issue by glenne** [adafruit/Adafruit_nRF52_Bootloader#190]
**Describe the bug**
All pull requests are failing checks due to build errors:

`/bin/sh: 1: arm-none-eabi-gcc: not found`

**To Reproduce**
Submit a pull request or view any of the recent pull requests.

**Expected behavior**
Builds do not fail unless a compiler syntax error is present.

**Comment by hathach** [comment]
thanks for the issue, it is due to toolchain installation path changes, and is just fixed. Please merge/rebase your PR from latest master.

**Comment by glenne** [comment]
Thanks.  I've updated my PR.
