### ISSUE TITLE
Memory partition on nRF52840 board (Itsy Bitsy)

### ISSUE THREAD

**Issue by yankobogdan** [adafruit/Adafruit_nRF52_Bootloader#203]
Hi
I am using Itsy Bitsy nRF52840 with Arduino IDE and the latest bootloader from Adafruit
The problem I've got stuck it's that I am using Adafruit_LittleFS to store files, I need to store ~200kB in flash so after resetting that part of memory wouldn't change, but the current bootloader leaves just 28kB for User Data. Is there any trick in how I can change the partition in the easiest way?
I imagine this like a change memory address in the current bootloader just to swap some memory from Application to User Data. But don't know where to dig in. 

Any help appreciated

**Comment by hathach** [comment]
This is not an enhancement, for question please post in Adafruit support forum
