### ISSUE TITLE
How to flash uf2 bootloader / circuitpython on pitaya go

### ISSUE THREAD

**Issue by rcmz** [adafruit/Adafruit_nRF52_Bootloader#216]
Hello I’m trying to flash the uf2 bootloader on my pitaya go in order to install circuitpython but I’m having trouble.

If I try to flash `pitaya_go_bootloader-0.6.1_s140_6.1.1.zip` using this command `adafruit-nrfutil dfu serial -pkg pitaya_go_bootloader-0.6.1_s140_6.1.1.zip -p /dev/ttyACM0 -b 115200` I get a `serial.serialutil.PortNotOpenError: Attempting to use a port that is not open` error

If I use the nrf programmer desktop application and try to write `pitaya_go_bootloader-0.6.1_s140_6.1.1.hex` I get a `DFU failed: Error message for known extended error code from DFU target: The init packet does not contain a signature. This bootloader requires DFU updates to be signed` error

Do you know how can I sign the hex / successfully flash the uf2 bootloader ?

**Comment by hathach** [comment]
Again, generally you will need a external programmer like jlink, but you should try to ask vendor that makes your hw board.
