### ISSUE TITLE
HID Support

### ISSUE THREAD

**Issue by jwillikers** [adafruit/Adafruit_nRF52_Bootloader#225]
**Is your feature request related to a problem? Please describe.**

I'd like to use the [hf2-rs](https://github.com/jacobrosenthal/hf2-rs) utility to develop in Rust for the Circuit Playground Bluefruit, like I currently do for the Circuit Playground Express.
This is not possible right now because the nRF52 bootloader does not support _HID_, which is necessary.
The samd bootloader, on the other hand, has this support available.

**Describe the solution you'd like**

I'd like Adafruit's nRF52 bootloader to add HID support like that available in the [uf2-samdx1](https://github.com/adafruit/uf2-samdx1) bootloader.

**Describe alternatives you've considered**

Manually creating a _UF2_ firmware file and using drag-and-drop or manually creating a DFU archive and uploading that with `adafruit-nrfutil`.

**Additional context**

The original issue is jacobrosenthal/hf2-rs#41.
HID support appears to mostly be implemented in [uf2hid.h](https://github.com/adafruit/uf2-samdx1/blob/master/inc/uf2hid.h), [uf2.h](https://github.com/adafruit/uf2-samdx1/blob/master/inc/uf2.h), and [hid.c](https://github.com/adafruit/uf2-samdx1/blob/master/src/hid.c) in uf2-samdx1.

**Comment by ladyada** [comment]
hiya - if you submit a PR we could review and merge it!
