### ISSUE TITLE
Classic UART Interface 

### ISSUE THREAD

**Issue by sergioxdev** [adafruit/Adafruit_nRF52_Bootloader#228]
Hello Guys

congratulations for the excellent work you are doing,
I wanted to ask you if the bootloader provides for the enabling of the classic UART interface, 
in order to communicate with another chip or maybe update the firmware via UART interface. 

Any info are accepted

**Comment by aqibnasim** [comment]
Hello @hathach, can you please direct me to the code where DFU for 832 is done over UART. Thanks
