### ISSUE TITLE
Request help to add new board -  Raytac MDBT50Q-DB-40

### ISSUE THREAD

**Issue by markbirss** [adafruit/Adafruit_nRF52_Bootloader#232]
Hi

Currently a bootloader exists for the MDBT50Q-RX, but not for the larger dev board MDBT50Q-DB-40

https://www.raytac.com/product/ins.php?index_id=89

https://www.raytac.com/product/ins.php?index_id=81

**Comment by hathach** [comment]
we don't have resource to support all boards, though if you make an PR we will be happy to review/merge it.

**Comment by markbirss** [comment]
Ok, here PR
https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/233
