### ISSUE TITLE
Make error.

### ISSUE THREAD

**Issue by HAO156** [adafruit/Adafruit_nRF52_Bootloader#235]
### Operating System

Linux

### INFO_UF2.TXT

NULL

### What happened ?

When I execute `make BOARD=feather_nrf52840_express all`, an error is reported The `"nrf.h"` file cannot be found.

### How to reproduce ?

Execute compile.

### Debug Log

<pre><font color="#8AE234"><b>van@van-virtual-machine</b></font>:<font color="#729FCF"><b>~/Desktop/BootLoader/Adafruit_nRF52_Bootloader</b></font>$ ls
<font color="#729FCF"><b>_build</b></font>  changelog.md  CODE_OF_CONDUCT.md  <font color="#729FCF"><b>lib</b></font>  LICENSE  <font color="#729FCF"><b>linker</b></font>  Makefile  README.md  <font color="#729FCF"><b>segger</b></font>  <font color="#729FCF"><b>src</b></font>  <font color="#729FCF"><b>tools</b></font>
<font color="#8AE234"><b>van@van-virtual-machine</b></font>:<font color="#729FCF"><b>~/Desktop/BootLoader/Adafruit_nRF52_Bootloader</b></font>$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

<font color="#8AE234"><b>van@van-virtual-machine</b></font>:<font color="#729FCF"><b>~/Desktop/BootLoader/Adafruit_nRF52_Bootloader</b></font>$ make BOARD=feather_nrf52840_express all
fatal: not a git repository: /home/van/Desktop/RAK4631_BootLoader/Adafruit_nRF52_Bootloader/.git/modules/lib/nrfx
CC dfu_ble_svc.c
In file included from <b>src/dfu_ble_svc.c:41</b>:
<b>lib/sdk11/components/libraries/bootloader_dfu/dfu_ble_svc.h:39:10:</b> <font color="#EF2929"><b>fatal error: </b></font>nrf.h: No such file or directory
   39 | #include <font color="#EF2929"><b>&quot;nrf.h&quot;</b></font>
      |          <font color="#EF2929"><b>^~~~~~~</b></font>
compilation terminated.
Makefile:382: recipe for target &apos;_build/build-feather_nrf52840_express/dfu_ble_svc.o&apos; failed
make: *** [_build/build-feather_nrf52840_express/dfu_ble_svc.o] Error 1
<font color="#8AE234"><b>van@van-virtual-machine</b></font>:<font color="#729FCF"><b>~/Desktop/BootLoader/Adafruit_nRF52_Bootloader</b></font>$ ls
<font color="#729FCF"><b>_build</b></font>  changelog.md  CODE_OF_CONDUCT.md  <font color="#729FCF"><b>lib</b></font>  LICENSE  <font color="#729FCF"><b>linker</b></font>  Makefile  README.md  <font color="#729FCF"><b>segger</b></font>  <font color="#729FCF"><b>src</b></font>  <font color="#729FCF"><b>tools</b></font>
<font color="#8AE234"><b>van@van-virtual-machine</b></font>:<font color="#729FCF"><b>~/Desktop/BootLoader/Adafruit_nRF52_Bootloader</b></font>$ 
</pre>

### Screenshots

![Uploading image.png…]()

**Comment by hathach** [comment]
Read the readme for check out submodule
