### ISSUE TITLE
MSC/UF2 to upgrade bootloader + SD

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Bootloader#24]
So far only DFU Serial could upgrade Bootloader + SD combo, uf2 should also do this as well. With a set of specific requirement e.g
- family option is different than one used by application firmware
- SD + bootloader must be upgraded at the same time to make sure that are in sync and work as expected
- SD data contains must be check to make sure it is S140
- uf2 of bootloader contain VID/PID which is used to prevent upgrading to incompatible board.

**Comment by dhalbert** [comment]
On atmel-samd UF2, the UF2 bootloader cannot update itself directly. Instead, you load a update program into non-bootload (user) space which then rewrites the bootloader. See the update-bootloader*.ino and .uf2 files in the UF2 release: https://github.com/adafruit/uf2-samdx1/releases/latest

**Comment by hathach** [comment]
it is doable with nrf52, we are doing it with cdc interface. it could upgrade itself via cdc packet. Maybe it is not too difficult to get it work with uf2

**Comment by hathach** [comment]
bootloader + SD uf2 image will have an different uf2 family ID to prevent accident or corrupted image from normal application uf2.
