### ISSUE TITLE
document how to enter bootloader on various boards

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_nRF52_Bootloader#25]
e.g., on PCA10056, must hold down button1 while pressing reset. Describe what other buttons do as well.

Thanks - you told me this in discord, but I'm not sure it's written down anywhere else.

**Comment by hathach** [comment]
it is listed here in the feature issue, on pca10056, button1 is DFU, button2 is FRST.
https://github.com/adafruit/Adafruit_nRF52_Bootloader/issues/6

**Comment by dhalbert** [comment]
Could you put that info in the README?

**Comment by hathach** [comment]
sum up
- DFU = gnd + reset : CDC + UF2
- DFU = gnd + FRST = GND + reset : OTA
- FRST + reset = clear application
- adafruit-nrfutil --touch 1200 option --> CDC only

**Comment by ladyada** [comment]
i will add more details here as well
https://learn.adafruit.com/admin/guides/2074/editor/13384

**Comment by hathach** [comment]
@dhalbert @ladyada yeah, I will do it to the readme.md as well

**Comment by hathach** [comment]
just add how to use section, though I am not a good writer at all ( not even close ). Please feel free to edit them.

**Comment by ladyada** [comment]
me too, i can do the writing, i just need the correct commands to run :)

**Comment by hathach** [comment]
Great, I will just throw out commands and descriptive text from now on kaka :D

**Comment by ladyada** [comment]
ok please add/edit here as necessary, https://learn.adafruit.com/circuitpython-on-the-nrf52

**Comment by christophepersoz** [comment]
Is there an access to FRST and DFU on pins for the nRF52840 express dongle? Can't find any documentation on this even on the schematic. Thanks
