### ISSUE TITLE
Double-click reset possible?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_nRF52_Bootloader#26]
@hathach @ladyada @tannewt 

We were talking a few days ago about not being able to detect double-click in the bootloader because the nRF52 clears out everything on a hard reset. However, the [nrf52840 data sheet](http://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.0.pdf) in section 5.3.6.8 (page 69) says:

>Note: The RAM is never reset, but depending on a reset source the content of RAM may be
corrupted.

So I just want to double-check if someone has actually tried this and confirmed that leaving a sentinel value in a RAM location doesn't work.

**Comment by hathach** [comment]
Last time I tried, it is totally failed, i will give it another with multiple sram bank as scratch data

**Comment by hathach** [comment]
@dhalbert @ladyada  I just get the double reset work with nrf52. Yeah, you guys are so right suspecting my failed attemppt previously kk. I think the problem I run into previously is first trying with some register, then try to use a random SRAM. but the SRAM is clear by startup script ( not hardware). We need to specify the linker with NOLOAD to spare that SRAM location. Feel so good now. I will clean up and push the update.

**Comment by hathach** [comment]
There is lots of works for releasing nrf52832 feather back then, so hahaha, I gave up so soon on this. Thanks for bringing this up :D

**Comment by hathach** [comment]
Update:  the double reset really **DOES NOT** work with nrf52832, only work with nrf52840, same code. No matter how I tried :D  There is a reason for my giveup  afterall  !!!

**Comment by ladyada** [comment]
wow! ok well we have auto-bootloader for '532 so lets add for nrf52840 only

**Comment by dhalbert** [comment]
that's weird, hope it continues to work! Thanks for the thorough testing. We should try it on multiple 52840 boards to make sure.

**Comment by hathach** [comment]
Yeah, please test it to see if that work.  840 work with my first try, so I think it will be OK.

**Comment by hathach** [comment]
Yeah, please test it to see if that work.  840 work with my first try, so I think it will be OK.

**Comment by dhalbert** [comment]
Works! Great!

**Comment by hathach** [comment]
Yeah, the 840 works right away. Currently 832 share same code (I didnt #ifdef to opt it out). Still it refuses to work. I think I did put 832 under debugger to test sram before, and convinced that  its sram got clear. I will check noridc devzone, I remembered seeing a relevant topic back then.

**Comment by dhalbert** [comment]
Works on my two PCA10056 boards. I think we can declare success!

**Comment by ladyada** [comment]
tested on my PCA - works great :)

**Comment by ladyada** [comment]
tested on Feather 840 as well - works great for doubleclicking
i updated the guide as well https://learn.adafruit.com/circuitpython-on-the-nrf52
