### ISSUE TITLE
Support for Softdevice S140 7.0.1 and openthread library

### ISSUE THREAD

**Issue by Brezensalzer** [adafruit/Adafruit_nRF52_Bootloader#260]
Hello,
I did some experiments with [Thread networks and an ItsyBitsy nRF52840 board](https://github.com/Brezensalzer/ot-nRF52-experiments) and found this [Arduino package for Adafruit nRF52840](https://github.com/soburi/openthread_nrf52_arduino) boards and openthread support. You need to burn a new bootloader with a J-Link programmer - that is rather scary to me.
Is it possible to update the "official" uf2 bootloader to Softdevice S140 7.0.1 (used for Thread networking) and make the openthread library via the Adafruit nRF52840 Arduino package available?
Thanks in advance

**Comment by hathach** [comment]
Currently we have no plan to support openthread or SD v7. Just get an mini jlink and try it out. It isn't that scary.
