### ISSUE TITLE
Type casting for ((USB_DESC_VID << 16) | USB_DESC_UF2_PID)

### ISSUE THREAD

**Issue by tadakado** [adafruit/Adafruit_nRF52_Bootloader#262]
https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/fc487794b384ec915abccdaed12a0f2730082b90/src/usb/uf2/ghostfat.c#L509

Do we need (uint32_t) for this?
I have an error when USB_DESC_VID >= 0x8000.

**Comment by hathach** [comment]
can you try to define both VID and PID with suffix unsigned e.g `0x8000u` to see if that work. If not we would need to cast it

**Comment by tadakado** [comment]
It works! Perfect!!
