### ISSUE TITLE
CircuitPython on the nRF52 ----> Compiling latest bootloader from source

### ISSUE THREAD

**Issue by RoussetN** [adafruit/Adafruit_nRF52_Bootloader#264]
### Operating System

Windows 10

### INFO_UF2.TXT

i don't have any because i diseable the mass storage on my pca10056 J-link.

### What happened ?

I just finish to flash the Bootloader with nrfjprog and i don't get any error but to Compil the  latest bootloader from source i need to do the instruction below:

make BOARD=pca10056 clean
make BOARD=pca10056 sd
make BOARD=pca10056 flash

My cmd does not recognize "make" as an intern or extern expression, executable programm.

I already check and in your github there is an makefile so i don't understand my issu.

Can you help me?

Thank's 

Rousset Nathan

### How to reproduce ?

Following the "CircuitPython on the nRF52 " that you have write .

### Debug Log

![image](https://user-images.githubusercontent.com/101865717/162466810-14010c3c-01f2-4eee-80ed-9731c0c45c4d.png)

### Screenshots

<img width="383" alt="Issu" src="https://user-images.githubusercontent.com/101865717/162467260-a35587fe-a17e-4935-a70a-75a452f1c20d.png">

**Comment by hathach** [comment]
first of all, this is not an bug of this repo. This is purely environment/toolchain setup on your PC. For such how-to please ask on adafruit support forum, there is lots more users there to help you out.
