### ISSUE TITLE
Workflow-build fails with error code 2 while installing toolchains

### ISSUE THREAD

**Issue by ebastler** [adafruit/Adafruit_nRF52_Bootloader#265]
### Operating System

Linux

### INFO_UF2.TXT

None, issue happens when compiling the bootloader.

### What happened ?

When compiling a bootloader with github actions the action fails with an error during toolchain installation. I will link my failed workflow run, as that will give more information than I could provide in text form:
https://github.com/ebastler/Adafruit_nRF52_Bootloader/runs/6452117714

This is for my modified workflow, where I removed all boards but a custom one - exact same result occurs with the default workflow config and no changes.

### How to reproduce ?

1. Fork repository
2. Run "build" workflow
3. It will fail at "Install Toolchains"

**Comment by hathach** [comment]
issue is confirmed, seem like the ci build script need updated. Will fix this soon
