### ISSUE TITLE
MDK NRF52840 USB Dongle bricked after flashing latest bootloader

### ISSUE THREAD

**Issue by oddlama** [adafruit/Adafruit_nRF52_Bootloader#279]
### Operating System

Linux

### INFO_UF2.TXT

Not applicable, dongle is dead.

### What happened ?

I flashed the latest bootloader to my device, which seemed like it was successful. Afterwards, the device is unresponsive and doesn't show up as a flash drive.

It seems like I cannot enter the bootloader in any way. I tried double reset, different combinations of hooking up P0.18 (DFU) and P0.19 (FRESET). Only the power led is on, the other led never shows anything. Previously the second led was green when the bootloader was active.

This is the output of the flashing (seems successful).

```
$ adafruit-nrfutil --verbose dfu serial --package ~/Downloads/mdk_nrf52840_dongle_bootloader-0.7.0_s140_6.1.1.zip -p /dev/ttyACM0 -b 115200 --singlebank --touch 1200
Upgrading target on /dev/ttyACM0 with DFU package /home/malte/Downloads/mdk_nrf52840_dongle_bootloader-0.7.0_s140_6.1.1.zip. Flow control is disabled, Single bank, Touch 1200
Touched serial port /dev/ttyACM0
Opened serial port /dev/ttyACM0
Starting DFU upgrade of type 3, SoftDevice size: 151016, bootloader size: 39000, application size: 0
Sending DFU start packet
Sending DFU init packet
Sending firmware file
########################################
########################################
########################################
########################################
########################################
########################################
########################################
########################################
########################################
############
Activating new firmware

DFU upgrade took 20.59038782119751s
Device programmed.
```

### How to reproduce ?

See above for command.

**Comment by hathach** [comment]
have you tried double tap/reset method to enter bootloader ?

**Comment by oddlama** [comment]
> have you tried double tap/reset method to enter bootloader ? 

I have, I am 100% sure it is bricked. I'm not new to this and will probably be able to recover it using a J-link device.

> Therefore the hw is not supported since hw is not available for testing/verifying.

No problem, I understand that you don't want to support devices that you don't have access to or sell. But if you say this board is not supported, why is it listed at the very top of your readme? This made me at least think it was officially supported. It might be a good idea to add a warning about this.

![image](https://user-images.githubusercontent.com/31919558/195996940-cb36206a-c976-4c34-9cbd-f4f98deffa21.png)

**Comment by hathach** [comment]
I have update readme accordingly.
