### ISSUE TITLE
DFU OTA with NRF Connect stuck at 100%

### ISSUE THREAD

**Issue by ericlangel** [adafruit/Adafruit_nRF52_Bootloader#287]
### Operating System

Android 12

### INFO_UF2.TXT

-

### What happened ?

I do the DFU Update with NRF Connect App.
The Distribution Package (.zip) is generated by Arduino (NRF52 Adafruit).

9 of 100 times the Update fails at 100% and the NRF is bricked. -> i have to flash the Bootloader again.
What should i do?

### How to reproduce ?

Do the DFU Update with NRF Connect

**Comment by Montvydas** [comment]
I also have the same issue, take a look at [my comment on Nordic-DFU-Library](https://github.com/NordicSemiconductor/Android-DFU-Library/issues/333). As per the comment, a temporary solution is to use an older version of nRF Connect App e.g. 4.24.3. I would like to know what a proper fix should be, but it might be the fault of Nordic-DFU-Library or Adafruit nRF52 Bootloader.
