### ISSUE TITLE
Support for ebyte_e104_bt5040u

### ISSUE THREAD

**Issue by xiaofami** [adafruit/Adafruit_nRF52_Bootloader#340]
**Ebyte E104 BT5040U** is a pin2pin clone of Nordic nRF52840 USB Dongle ,which is well documented and very cheap. The details could be found here: https://www.cdebyte.com/products/E104-BT5040U . Could we get support for it in the future ?

![image](https://github.com/user-attachments/assets/b83cbaac-3eaf-454d-938c-e9f064f966f1)
![image](https://github.com/user-attachments/assets/0477b953-8f8d-49bc-a79e-bc19cb31ae3c)
![image](https://github.com/user-attachments/assets/194475be-5e22-4674-849e-e8fbc7a3ebb8)

**Comment by hathach** [comment]
please support an PR, we will review and merge if it is good
