### ISSUE TITLE
OS complain when copying current.uf2 after uploaded via Arduino (DFU CDC)

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Bootloader#37]
Reproduce: upload blink sketch from arduino and try to copy it from bootloader will cause the issue. This issue does not happen when DFU with uf2 file.

Note: usb analyzer doesn't show any failed transaction, everything seems fine. It is possibly data contents issue.

![image](https://user-images.githubusercontent.com/249515/50299396-0bcb2d80-04b4-11e9-813d-b875401132b6.png)

**Comment by jpconstantineau** [comment]
I see this issue also on windows 10.

**Comment by hathach** [comment]
thank for confirmation, we are working on the fix :)
