### ISSUE TITLE
pca10059.h Proposed Changes

### ISSUE THREAD

**Issue by jpconstantineau** [adafruit/Adafruit_nRF52_Bootloader#39]
Proposing a few changes here since I don't have the tooling to compile the bootloader to test if any of the changes break anything.

1 - Change how the buttons are defined. Use _PINNUM() function instead of obscure binary shift notation. (I think there is an error on the pins used but I am not sure) P1.06 is the button and P1.10 is the pin for the "second" button

2 - Add PRODUCT_NAME  and VOLUME_LABEL  defines.
Suggesting "DONGLE_BOOT" or "PCA10059_BOOT" as VOLUME_LABEL

3 - Add RGB LED as second LED instead of secondary LED (similar to the particle boards)
 #define LED_RGB_RED_PIN           _PINNUM(0, 8)
 #define LED_RGB_GREEN_PIN       _PINNUM(1, 9)
 #define LED_RGB_BLUE_PIN          _PINNUM(0, 12)

**Comment by hathach** [comment]
I have update to match the No.1 since it is easy

**Comment by hathach** [comment]
for 2) DONGLE_BOOT is too generic, there is also other dongle based such as mdk. PCA10059_BOOT is too long, the volume must be at max 11 characters.
for 3) If possible please submit PR since I still haven't soldered SMD header to my dongle yet :D

**Comment by hathach** [comment]
closed due to lack of interaction

**Comment by jpconstantineau** [comment]
OK to close...  I haven't had a chance to look at this in a while and with all the recent changes, it's quite likely that some of the changes that happened took care of this (will do a PR if needed - when I have a chance)  Thanks
