### ISSUE TITLE
Use without softdevice

### ISSUE THREAD

**Issue by antst** [adafruit/Adafruit_nRF52_Bootloader#74]
Hello,

I am trying to adopt this bootloader for use in non-BLE application, without softdevice.
Mainly due to UF2. 

By commenting out -DBLE_STACK_SUPPORT_REQD and -DSOFTDEVICE_PRESENT and excluding compilation of few BLE-specific binaries and wrapping in ifdef few BLE-specific calls I was able to compile it, but it doesn't work for me. (I test on nrf52840-DK with flashed MBR)
Looking that there are those defines, it looks like somebody had in mind use of this boot-loader in non-BLE application. 
Were there attempts to run without softdevice? Any suggestions?

Thanks!

**Comment by xiongyihui** [comment]
+1
want to use it with zephyr or mynewt which has its own ble stack

**Comment by hathach** [comment]
related to #30

**Comment by hathach** [comment]
implemented by #128
