### ISSUE TITLE
Circuit Playground Bluefruit forcing OTA DFU mode

### ISSUE THREAD

**Issue by khanning** [adafruit/Adafruit_nRF52_Bootloader#76]
After applying the latest precompiled bootloader + SD for the Circuit Playground Bluefruit (`circuitplayground_nrf52840_bootloader-0.2.12_s140_6.1.1`), the device forces itself into OTA DFU mode (purple neopixel ring).  
  
Holding down either button while resetting allows the device to enter CDC/UF2 DFU mode. However, on subsequent resets the device forces itself back into OTA DFU mode so there doesn't seem to be a way to run application firmware after a reset.

**Set up**
  - Circuit Playground Bluefruit
  - Mac OSX 10.14.6

**To Reproduce**
1. Place Circuit Playground Bluefruit in CDC/UF2 DFU bootloader mode 
2. Apply new bootloader + SD  
`adafruit-nrfutil --verbose dfu serial --package circuitplayground_nrf52840_bootloader-0.2.12_s140_6.1.1.zip -p /dev/tty.usbmodemXX -b 115200 --singlebank --touch 1200`
3. After receiving success message, the device enters OTA DFU mode (purple neopixel ring)  
```
Starting DFU upgrade of type 3, SoftDevice size: 151016, bootloader size: 29200, application size: 0
Sending DFU start packet
Sending DFU init packet
Sending firmware file
########################################
########################################
########################################
########################################
########################################
########################################
########################################
########################################
################################
Activating new firmware

DFU upgrade took 19.310901165008545s
Device programmed.
```
4. Enter CDC/UF2 DFU mode by holding either button 1 or 2 and resetting the device.
5. Apply application firmware using either CDC or UF2.
6. The application runs properly.
6. Reset the device. It enters OTA DFU mode.

**Comment by hathach** [comment]
should be fixed by pr #77 . Thank you very much for reporting and fixing the issue.
