### ISSUE TITLE
OTA DFU succeeds but does not start application

### ISSUE THREAD

**Issue by zwells** [adafruit/Adafruit_nRF52_Bootloader#79]
I've compiled the bootloader for my custom nrf52832 boards (different button/led pins) and merged it with s132 softdevice for my own hex file.  It runs fine, OTA DFU on the Bluefruit app succeeds, but when I restart my board one LED does a fast pwm sequence and then both LEDs go solid on without starting the application.

 I export the compiled binary hex file from Arduino IDE, then perform the following:

adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application sketch.ino.feather_nrf52832.hex package.zip

Then I unzip that file, and use the .hex file, and the .dat file (that's the init file that Bluefruit requires).

I'm hoping it's as simple as just having to change an address definition.

**Comment by zwells** [comment]
My sketches run on my bootloader if I upload through Jlink with Arduino IDE and hold Shift for _Upload with programmer_

**Comment by hathach** [comment]
I will close this since it is not bootloader issue, you are probably missing a step or two with the OTA.

**Comment by zwells** [comment]
You are correct! It is working now. Thank you!
