### ISSUE TITLE
Automate builds

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_Bootloader#8]
Hey Thach, since you're doing a ton of work in this repo would it be helpful to have automatic builds on commits via travis?

Dan & I could get that going for you so that the hex files appear on S3 - then you wouldn't have to keep committing binaries as you build and we would have less risk of out-of-sync bootloaders between this and circuitpython repo!

Please let us know :)

**Comment by hathach** [comment]
Got it, no problem, I will add the .travis file to auto build. Then ping you for the S3 upload script.

Note: bootloader + SD combo is upgradable, we should keep an binary for each "release verion", so far nrf52832 have v2 and v5 (there is v6 coming to be consistent with nrf52840).

**Comment by dhalbert** [comment]
@hathach Just to be clear you haven't started on travis-ing this yet, have you? I will work on this but just want to make sure I'm not duplicating something you haven't checked in yet.

**Comment by hathach** [comment]
I guess it is safe to close this now. Feel free to open if it isn't
