### ISSUE TITLE
Help getting MDK nrf52840 USB Dongle to appear?

### ISSUE THREAD

**Issue by henrygab** [adafruit/Adafruit_nRF52_Bootloader#81]
I'm trying to get the MDK nrf52840 USB Dongle (supported since PR #49).  <details><summary>I start by programming the bootloader.</summary>

<p>

1. Download [v0.2.12](https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases/download/0.2.12/mdk_nrf52840_dongle_bootloader-0.2.12_s140_6.1.1.hex) bootloader
2. Fully erase the device: `nrfjprog --family nrf52 --eraseall`
3. Program the bootloader: `nrfjprog --family nrf52 --program .\adafruit-circuitpython-makerdiary_nrf52840_mdk_usb_dongle-en_US-4.1.0.hex --sectoranduicrerase --reset`

</details>

Dongle now boots with green LED lit, which I think is a good sign.  However, reading the memory using the JLink doesn't show the bootloader in memory?

I am also having trouble getting the device to appear as a USB storage device.  I've tried grounding the reset pin multiple times within 500ms, but it never enumerates as a USB device, further suggesting a problem writing the bootloader.

@gpshead , @hathach … Is there some simple step I'm missing to get this board into DFU mode? (USB UF2 firmware upload mode?)

<details><summary>Next steps:</summary>

<p>

4. Program the softdevice (s140_nrf52_6.1.1_softdevice.hex)
5. Program the CircuitPython file ([adafruit-circuitpython-makerdiary_nrf52840_mdk_usb_dongle-en_US-4.1.0.hex](https://github.com/adafruit/circuitpython/releases/download/4.1.0/adafruit-circuitpython-makerdiary_nrf52840_mdk_usb_dongle-en_US-4.1.0.hex))

The above can work from nRF Connect using the JLink, but would prefer to use UF2 to update the application layer going forward.

</details>

Thanks!

**Comment by ladyada** [comment]
try following https://learn.adafruit.com/circuitpython-on-the-nrf52/nrf52840-bootloader
