### ISSUE TITLE
Support for Holyiot 17120 USB dongle (nRF52840)

### ISSUE THREAD

**Issue by stich86** [adafruit/Adafruit_nRF52_Bootloader#86]
**Is your feature request related to a problem? Please describe.**
I'm trying to use PCA10059 bootloader on this board but without success. Also this board doesn't have any button to enter DFU, so the only way to rescue is to use a J-Link programmer

**Describe the solution you'd like**
Support for this board, and may be software-trigger DFU

**Describe alternatives you've considered**

**Additional context**
[HOLYIOT-17120-NRF52840 (0.8mm)-SCH.pdf](https://github.com/adafruit/Adafruit_nRF52_Bootloader/files/3857720/HOLYIOT-17120-NRF52840.0.8mm.-SCH.pdf)
[YJ-17120-nRF52840 datasheet.pdf](https://github.com/adafruit/Adafruit_nRF52_Bootloader/files/3857721/YJ-17120-nRF52840.datasheet.pdf)

**Comment by hathach** [comment]
we don't have the hardware, but will gladly merge it if you could submit an PR
