### ISSUE TITLE
[Bug]Adafruit_nRF52_Bootloader.emProject nrfx.h: No such file or directory SES

### ISSUE THREAD

**Issue by mehmetcanbalci-Notrino** [adafruit/Adafruit_nRF52_Bootloader#89]
I downloaded current version of adafruit/Adafruit_nRF52_Bootloader
Setup_EmbeddedStudio_ARM_v430c_win_x64.exe installed.
Then i downloaded https://github.com/NordicSemiconductor/nrfx.

I run SES , then File - > Open solution.
I have opened ...\src\segger\Adafruit_nRF52_Bootloader.emProject file 

Build-> F7 

I got this error.

Building ‘Adafruit_nRF52_Bootloader’ from solution ‘Adafruit_nRF52_Bootloader’ in configuration ‘Feather52832’
  Compiling ‘SEGGER_RTT.c’
  Compiling ‘SEGGER_RTT_SES.c’
  Compiling ‘main.c’
    nrfx.h
    main.c
    nrf.h: No such file or directory
  Compiling ‘dfu_ble_svc.c’
    dfu_ble_svc.c
    nrf.h: No such file or directory
Build failed

Windows10 64bit2

I have added src folder from "adafruit/Adafruit_nRF52_Bootloader" and mdk folder from https://github.com/NordicSemiconductor/nrfx into Projetcs->Options->Preprocessors->User Include Directories.

How can i solve this problem . Interestingly dfu_ble_svc.h file can not find the nrf.h file but same file can be found by nrfx_common.h in same project .

**Comment by hathach** [comment]
ses is out of sync, please use the makefile. I will fix this the next time I have to work with ses for this project
