### ISSUE TITLE
CF2 support

### ISSUE THREAD

**Issue by mmoskal** [adafruit/Adafruit_nRF52_Bootloader#92]
**Describe the solution you'd like**

UF2 defines a format to store configuration data about the board in the bootloader area, see https://github.com/microsoft/uf2/blob/master/cf2.md

This is currently used primarily by MakeCode Arcade to define where the button/screen pins are, but is extensible. This is supported in SAMD51 and STM32F4 bootloaders.

Could we have maybe 1k of bootloader area reserved for this?

**Comment by mmoskal** [comment]
CC @ladyada @dhalbert

**Comment by hathach** [comment]
This is a great idea, 1KB is not a problem or whatsover, we does reserve several of KBs for future extensions as this
